version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/nodejs/Dockerfile"
    container_name: "bitcoin_webserver"
    restart: 'always'
    ports:
      - 80:3000
    volumes:
      - ./:/app
